### PR TITLE
French author relevancy VUF-6064

### LINKED ISSUE #175: French author search VUF-6064
This is a French author. Why does the first listing for a original text in French come in Position 16 in the search results, after more than 10 Spanish translations?

https://searchworks.stanford.edu/?f%5Bauthor_person_facet%5D%5B%5D=Vargas%2C+Fred&q=Vargas&search_field=search

https://jirasul.stanford.edu/jira/browse/VUF-6064

### PR DESCRIPTION
**Pull request by shelleydoljack**
Closes #175

### CODE REVIEW

**Comment by shelleydoljack** [comment]
It's not clear to me what the expected relevancy should be. The search is for the author, not a particular work the author has produced. It seems the expectation is that original texts would rank higher than translated texts. I don't think this is possible given the metadata we have. The tests in this PR are the best I could come up with to address #175 .

**Comment by mejackreed** [comment]
Agreed that this is complex. I'm not sure how to address the original intent of #175 appropriately. Is it possibly that we just can't write a test for some of these?

What the user proposes makes a lot of sense, but seems impossible based of the current data we build relevancy off of.  Can we chat real quick F2F about how to proceed?

**Comment by cbeer** [comment]
I think it's also fair to add the test and mark it as pending.

**Comment by cmh2166** [comment]
Note Irina's comment on the original JIRA ticket:

```
Dear Nicolas, 

Thank you very much for your feedback. 

Language of publication is not one of the factors determining relevancy ranking in SearchWorks. 

Thanks, 

Irina 
```

That feels like it supports saying we don't capture & use metadata in such a way that relevancy could be changed here. We can leave this open, I believe, and queue it as a question for the Gryphon Search folks to discuss how they want to handle manifestations rankings for translations.

**Comment by cmh2166** [comment]
Follow-up on this based on stand-up discussion this morning: don't bother writing a baseline test that addresses the concern in the ticket, given limitations of metadata to meaningfully test this & uncertainty about how Gryphon-search wants to set relevancy expectations for this use case. Leave the jira ticket marked as gryphon-search (meaning they need to review + write up specs for relevancy there that we can then add as a test later here). 

@shelleydoljack @mejackreed @cbeer does this makes sense?

**Comment by shelleydoljack** [comment]
I moved the jira ticket to https://jirasul.stanford.edu/jira/browse/SW-1986 so that it will get on gryphon-search's radar. Do we want to close this PR or merge it?

**Comment by shelleydoljack** [comment]
The general consensus from gryphon-search is that the language of original works should be boosted above translated works. Users should be able to use the Language facet to drill down to the work they want. I added a pending test for this desired user experience.

**Comment by shelleydoljack** [comment]
Closing old PR.

**Pull request closed without merging**
