### PR TITLE
Apply modern rspec practices

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by cbeer** [comment]
I don't understand why `./spec/cjk/japanese_title_spec.rb:33` is now failing on travis

**Comment by mejackreed** [comment]
Yep.. I've kicked the build a few times

**Comment by mejackreed** [comment]
Maybe it wasn't testing what we thought it was previously?

**Comment by cbeer** [comment]
Ah, I found it.. it turns out `lang_limit` gets mutated by some of those helper methods, so when it changed scope, it ended up evaluated later. ugh.

**Pull request merged**
